# .github/release-drafter.yml

template: |
  ## 🎉 What's Changed

  $CHANGES

  ---
  🧪 **Tests:** $TESTS
  🔒 **Security:** $SECURITY
  📦 **Dependencies:** $DEPENDENCIES

categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - bugfix
  - title: 🧰 Maintenance
    labels:
      - maintenance
      - refactor
  - title: 🛠️ Infrastructure
    labels:
      - infrastructure
      - ci
  - title: 🔒 Security
    labels:
      - security
      - vulnerability
  - title: 📦 Dependencies
    labels:
      - dependencies
      - dependency-update

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: 'No changes'

version-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
name-template: 'Release v$NEXT_PATCH_VERSION'

generate-notes: true

exclude-labels:
  - 'wontfix'
  - 'invalid'

contributors:
  enabled: true
  only-merges: true
