[pytest]
testpaths = tests
asyncio_mode = auto
pythonpath = .
filterwarnings =
    ignore:Inheritance class HomeAssistantApplication from web.Application is discouraged:DeprecationWarning:homeassistant\.components\.http
