name: HACS Validation

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Validate with HACS
    runs-on: ubuntu-latest
    steps:
      # Repository auschecken
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # HACS-Aktion ausführen
      # Run HACS action
      - name: HACS Action
        uses: hacs/action@main
