# .github/workflows/release.yaml

name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Reagiert auf Tags wie v1.0.0

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout Code
        uses: actions/checkout@v3

      # GitHub Release erstellen
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            ## 🎉 What's Changed

            ${{ steps.generate_release_notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
