name: Mark and Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Täglich um Mitternacht

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Dieses Issue wurde als inaktiv markiert, da es seit 30 Tagen keine Aktivität gab.'
          stale-pr-message: 'Dieser Pull Request wurde als inaktiv markiert, da er seit 30 Tagen keine Aktivität zeigte.'
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'stale'
